name: whiteshorts
description: >-
  TBC
version: 0.1.0
homepage: TBC
documentation: TBC

environment:
  flutter: '>=3.22.0'
  sdk: '^3.9.0'

dependencies: 
  supabase_flutter: ^2.5.0
  intl: ^0.19.0
  google_fonts: ^6.3.2

