name: Publish predictions to Supabase

on:
  
    #push:
       #branches: ["development"]

    workflow_dispatch: {}

permissions:
  contents: read

jobs:
  broadcast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install typer duckdb joblib scikit-learn statsmodels pandas pyarrow requests
      - name: Install package
        working-directory: ./packages/whiteshorts_broadcast
        run: |         
          pip install -U pip
          pip install -e .
          cd ..
      - name: Publish predictions to Supabase
        id: Publish_Results_Predictions
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          SUPABASE_TABLE: predictions
          WS_BACKEND: supabase
        run: |
              python - << 'PY'
              import os, pandas as pd
              from whiteshorts_broadcast import publish_results, BroadcastConfig, find_latest_csv
              csv_path = find_latest_csv("data/parquet/predictions_*.csv") 

              df = pd.read_csv('data/parquet/predictions_2025-11-13_6401573150754847906.csv')  # or the exact path you just wrote
              df2 = pd.read_csv('data/parquet/predictions_2025-11-14_8448672720108401472.csv')  # or the exact path you just wrote
              df3 = pd.read_csv('data/parquet/predictions_2025-11-15_2574938582593037793.csv')  # or the exact path you just wrote
              df4 = pd.read_csv('data/parquet/predictions_2025-11-16_4318488430611622696.csv')  # or the exact path you just wrote


              cfg = BroadcastConfig(
              backend='supabase',
              supabase_url=os.environ['SUPABASE_URL'],
              supabase_anon_key=os.environ['SUPABASE_SERVICE_KEY'],
              supabase_table='predictions_for_broadcast',
              upsert_on=['date','player_id','target'])
              publish_results(df, cfg)
              publish_results(df2, cfg)
              publish_results(df3, cfg)
              publish_results(df4, cfg)
              PY
